# Generated by Django 4.2.7 on 2023-11-30 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realisator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('surname', models.CharField(max_length=90)),
                ('resume', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
                ('summary', models.TextField(null=True)),
                ('date', models.DateField()),
                ('realisator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='film.realisator')),
                ('realisator_bis', models.ManyToManyField(blank=True, related_name='posts', to='film.realisator')),
            ],
        ),
    ]
