# Generated by Django 4.2.7 on 2023-12-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_rename_realisator_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.IntegerField(),
        ),
    ]
