# Generated by Django 4.2.7 on 2023-12-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_movie_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.DurationField(),
        ),
    ]
